### ISSUE TITLE
HR should be able to see a list of employees

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Workforce-Mgt#1]
**Given** an HR employee wants to view employees
**When** the employee clicks on the Employees item in the navigation bar
**Then** all current employees should be listed with the following information

1. First name and last name
1. Department
- [x] On clicking employees in nav it will display the list of employees.

**Comment by Staffmaster00** [comment]
Use pug to do an "ng-repeat" after getting the data.

**Comment by Staffmaster00** [comment]
We will have to re-add departments at some point.
