### ISSUE TITLE
HR should be able to add an employee

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Workforce-Mgt#2]
**Given** the user is viewing the list of employees
**When** the user clicks the Create New link
**Then** a form for be displayed on which the following information can be entered

1. First name
1. Last name
1. Employment start date
1. Select a department from a drop down
- [x] Have employee and department data.
- [x] Use a form to add the employee to database.

**Comment by Staffmaster00** [comment]
So after the user hits create new a function will get the department data and use it to help complete the user submitted form that posts to the database. (.date can be used from exercise.)

Create new redirects you to a new view/page where you submit the form.
