### ISSUE TITLE
HR should be able to view employee details

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Workforce-Mgt#3]
**Given** a user is viewing the employee list
**When** the user clicks on an individual employee
**Then** the user should be shown a detail view of that employee, and it must contain the following information

1. First name and last name
1. Department
1. Currently assigned computer
1. Training programs they have attended, or plan on attending

- [x] Employee names are links.
- [x] When clicked grabs employee data.

**Comment by Staffmaster00** [comment]
After clicking the employee tab the user can click individual employees and receive data on them based on id.

Needs to get all related tables for the employee. Reference https://drive.google.com/file/d/0BxlPYVvTVzcNUjNJeE56N0hCOGM/view?usp=sharing
