### ISSUE TITLE
HR should be able to edit an employee

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Workforce-Mgt#4]
**Given** user is viewing an employee
**When** user clicks on the Edit link
**Then** user should be able to edit the last name of the employee
**Or** change the department to which the employee is assigned
**Or** change the computer assigned to the employee
**Or** add/remove training programs for the employee to attend in the future

- [x] Able to get all relevant data.
- [x] After viewing employees, clicking on an employees name calls an edit form.
- [x] Able to submit edited data to the database.

**Comment by Adobe-Android** [comment]
I think that the employee last name could be a text field, but it looks like the dept, assigned computer, and training programs would have to be a drop-down menu. We also need to remember to check the current date and only allow them to add or remove training programs that are in the future.
