### ISSUE TITLE
HR should be able to create a department

### ISSUE THREAD

**Issue by gregkorte** [Lethal-Lemurs/Bangazon-Workforce-Mgt#6]
**Given** user is viewing all departments
**When** user clicks on the Create New link
**Then** a form should be presented in which the new department name can be entered

- [ ] After clicking the create new link then the user is presented with a form.
- [ ] Submit will create a new department in database.

**Comment by Adobe-Android** [comment]
What kind of data does a dept need? Name and the id?

**Comment by Staffmaster00** [comment]
So this is a post to departments, and when an employee is assigned to a department then the join table receives the data.
